repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: python3 -m flake8 lightnum/ lightnum/test/ --indent-size=2 --select=F,E112,E113,E203,E304,E502,E703,E71,E72,E731,W191,W6 --extend-ignore=E702,F401 --statistics -j4
        language: system
        always_run: true
        pass_filenames: false
      #- id: mypy
      #  name: mypy
      #  entry: python3 -m mypy lightnum/
      #  language: system
      #  always_run: true
      #  pass_filenames: false
      - id: tests
        name: tests
        entry: python3 -m pytest lightnum/test/test_lightnum.py
        language: system
        always_run: true
        pass_filenames: false
